on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    #runs-on: ${{ matrix.os }}
    runs-on: macos-latest
    # strategy:
    #   matrix:
    #     os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    # defaults:
    #   run:
    #     shell: bash

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # - name: Build main
      #   run: bazel build :main

      # - name: Run main
      #   run: bazel run :main      

      - name: Build
        run: |
          bazel build --spawn_strategy=local -c dbg --strip="never" ...

      - name: Test
        run: |
          bazel test --spawn_strategy=local -c dbg --strip="never" --test_output=errors ...
